spring:
  application:
    name: mars-test
  data:
    elasticsearch:
      uris: search-mars-elasticsearch-public-uw2r7acjr2w3tbmxbkbo5v62wq.ap-southeast-1.es.amazonaws.com
logging:
  level:
    org.springframework.data.elasticsearch.client: DEBUG
    org.springframework.data.elasticsearch: DEBUG
    org.elasticsearch.client: TRACE
    co.elastic.clients.transport.rest_client: TRACE

mars:
  upload:
    path: ./uploads
    file_service_url: http://localhost:8080/files/read/
